# Generated by Django 4.1.7 on 2023-05-06 05:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tcd', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DoctorSuggestions',
            new_name='DoctorSuggestion',
        ),
        migrations.RenameModel(
            old_name='PatientProblems',
            new_name='PatientProblem',
        ),
    ]
