# Generated by Django 4.1.7 on 2023-05-13 06:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tcd', '0002_rename_doctorsuggestions_doctorsuggestion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tcd',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='tcd',
            name='state',
            field=models.CharField(blank=True, choices=[('DOCTOR_SUGGESTION_SUBMITTED', 'DOCTOR_SUGGESTION_SUBMITTED'), ('PATIENT_INPUT_SUBMITTED', 'PATIENT_INPUT_SUBMITTED'), ('CLOSED', 'CLOSED'), ('OPEN', 'OPEN')], max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='doctorsuggestion',
            name='patient_problem',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='doctor_suggestion', to='tcd.patientproblem'),
        ),
    ]
