# Generated by Django 4.1.7 on 2023-05-13 07:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tcd', '0003_tcd_is_active_tcd_state_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctorsuggestion',
            name='patient_problem',
        ),
        migrations.AddField(
            model_name='patientproblem',
            name='doctor_suggestion',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='tcd.doctorsuggestion'),
        ),
    ]
