# Generated by Django 4.1.7 on 2023-05-14 12:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0003_doctor_doctor_id'),
        ('tcd', '0004_remove_doctorsuggestion_patient_problem_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tcd',
            name='doctor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tele_consultations', to='doctor.doctor'),
        ),
    ]
