# Generated by Django 4.1.7 on 2023-05-14 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tcd', '0005_alter_tcd_doctor'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PatientReviewImages',
            new_name='PatientReviewImage',
        ),
        migrations.RenameModel(
            old_name='PatientReviewVideos',
            new_name='PatientReviewVideo',
        ),
    ]
