# Generated by Django 4.1.7 on 2023-05-15 06:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tcd', '0007_doctorsuggestion_tcd'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientproblem',
            name='tcd',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='patient_problems', to='tcd.tcd'),
        ),
    ]
