# Generated by Django 4.1.7 on 2023-05-15 07:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tcd', '0008_alter_patientproblem_tcd'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientproblem',
            name='tcd',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patient_problems', to='tcd.tcd'),
        ),
        migrations.AlterField(
            model_name='patientproblemreview',
            name='tcd',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='patient_problem_reviews', to='tcd.tcd'),
        ),
    ]
