# Generated by Django 4.1.7 on 2023-05-21 10:57

import apps.tcd.model_helpers
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('tcd', '0009_alter_patientproblem_tcd_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientProblemExplanationImages',
            fields=[
                ('record_id', models.UUIDField(default=uuid.uuid4, help_text='common primary key for all the tables', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('image', models.ImageField(upload_to=apps.tcd.model_helpers.get_file_path_for_patient_tcd_documents)),
                ('patient_problems', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patient_problem_tcd_images', to='tcd.patientproblem')),
            ],
            options={
                'db_table': 'da_patients_problems_tcd_images',
                'abstract': False,
            },
        ),
    ]
