# Generated by Django 4.1.7 on 2023-04-30 10:37

import django.core.validators
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('record_id', models.UUIDField(default=uuid.uuid4, help_text='common primary key for all the tables', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('patient_reg_id', models.CharField(default='000', max_length=256)),
                ('name', models.CharField(max_length=256)),
                ('phone_number', models.CharField(blank=True, max_length=17, null=True, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'.", regex='^\\+?1?\\d{9,15}$')])),
                ('aadhar_no', models.CharField(max_length=12, null=True, unique=True)),
                ('aadhar_img', models.ImageField(blank=True, max_length=1023, null=True, upload_to='aadhar/patient')),
                ('is_insurance_exists', models.BooleanField(default=False)),
                ('insurance_name', models.CharField(max_length=256, null=True)),
                ('insurance_number', models.IntegerField(null=True)),
            ],
            options={
                'db_table': 'da_patient',
                'abstract': False,
            },
        ),
    ]
