"""
Django settings for main(WoofyaAPIDashboard) project.

Generated by 'django-admin startproject' using Django 2.1.1.

For more information on this file, see
https://docs.djangoproject.com/en/2.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.1/ref/settings/
"""
import os
from pathlib import Path

from main.logger import logging as custom_logging

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.1/howto/deployment/checklist/

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.dirname(__file__)))
APPS_DIR = os.path.join(BASE_DIR, 'apps')

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '&w)na9%0on(_+#$1#h@52ndc=+$&k3hp01pv^7=%f_ru%$$r2k'

ALLOWED_HOSTS = ['*']
AUTH_USER_MODEL = 'user.BaseUser'

LOGIN_URL = '/app/login/'
LOGOUT_URL = '/logout/'

API_DOMAIN_URL = '127.0.0.1:8000/'

LOGGING = custom_logging
# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django_extensions',
    'widget_tweaks',
    'rest_framework',
    # 'knox',
    'django_crontab',
    'corsheaders',
    # 'silk',
    'apps.commons',
    'apps.user',
    'apps.patient',
    'apps.doctor',
    'apps.tcd',
    'rest_framework.authtoken'
]
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.BasicAuthentication',
        'rest_framework.authentication.TokenAuthentication',
    ]
}
MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    # 'silk.middleware.SilkyMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'main.urls.urls'

TEMPLATE_PATH = os.path.join(BASE_DIR, 'templates')

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [TEMPLATE_PATH, ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'main.wsgi.application'

# Use the below snippet for Django Web Sockets/Channels
# ASGI_APPLICATION = 'main.routing.channel_routing'
# CHANNEL_LAYERS = {
#     "default": {
#         "BACKEND": "channels_redis.core.RedisChannelLayer",
#         "CONFIG": {
#             "hosts": [("localhost", 6379)],
#         },
#     },
# }

# Password validation
# https://docs.djangoproject.com/en/2.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/2.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True

TIME_INPUT_FORMATS = ['%I:%M %p']

DATA_UPLOAD_MAX_MEMORY_SIZE = 104857600  # your size limit in bytes

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.1/howto/static-files/

STATIC_ROOT = 'static/'
STATIC_URL = '/static/'
STATICFILES_FINDERS = (
    'django.contrib.staticfiles.finders.FileSystemFinder',
    'django.contrib.staticfiles.finders.AppDirectoriesFinder',
)

STATIC_PATH = os.path.join(BASE_DIR, 'site_static')  # Absolute path to the static directory
STATICFILES_DIRS = (
    STATIC_PATH,
)

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# https://github.com/ottoyiu/django-cors-headers/
CORS_ORIGIN_ALLOW_ALL = True
CORS_ALLOW_CREDENTIALS = True
CORS_ALLOW_HEADERS = (
    'x-requested-with',
    'content-type',
    'accept',
    'origin',
    'authorization',
    'sessionid',
)
CORS_EXPOSE_HEADERS = (
    'set-cookie',
    'sessionid',
)

# Accepted input types
VALID_IMAGE_FILE_TYPES = ['JPEG', 'PNG', 'JPG']

###########################
# CRON JOBS
###########################
# Docs
# https://pypi.org/project/django-crontab/
# https://crontab.guru/examples.html - cron tab duration examples

CRONJOBS = [
    ('0 10 * * *', 'apps.neighbourhoods.cronjobs.update_properties_count_for_neighborhoods.main'),
]

###########################
# EMAIL CONFIG
###########################

# TODO_CUSTOMIZATION
EMAIL_CONFIG = {
    "host": "smtp.gmail.com",
    "port": 465,
    "sender_email": "no-reply@nestsmarter.com",
    "sender_password": "NestSmarter2021@"
}

EMAIL_VERIFICATION_LINK_PATH = 'https://nestsmarter.com/verify-email/%s'

###########################
# TWILIO CREDENTIALS
###########################

TWILIO_ACCOUNT_SID = 'AC5a55dde0eaa84a66483a9f89eaed33d8'
TWILIO_AUTH_KEY = '76b5f65e560b152a8e6490aeb15a34fb'
TWILIO_FROM_PHONE_NUMBER = '+18437498814'

##################################################################################################
# GOOGLE SSO CREDENTIALS
##################################################################################################
GOOGLE_CLIENT_ID = '401628185678-tncjtvbjplohik8st4evcnog9b3ltlvo.apps.googleusercontent.com'
GOOGLE_CLIENT_SECRET = 'pyU-5MeFjkF7lUTPA_YKirV7'
GOOGLE_SIGNIN_SECRET_FILE = './config/client_secret_401628185678-tncjtvbjplohik8st4evcnog9b3ltlvo.apps.googleusercontent.com.json'

##################################################################################################
# FACEBOOK SSO CREDENTIALS
##################################################################################################
FB_APP_ID = '448210956604964'
FB_APP_SECRET = '771bb37196f037f8be01a129b1bca21f'
FB_REDIRECT_URL = '/oauth/facebook'

##################################################################################################
# HELLOSIGN CREDENTIALS
##################################################################################################
HELLOSIGN_USERNAME = 'nestsmarter@gmail.com'
HELLOSIGN_PASSWORD = '8KLgK6izVRABN!f'
HELLOSIGN_API_KEY = '5c069b12952f717a1fe4d9ab426721c88259b8e382f3538305c450bd8e38235f'

##################################################################################################
# APPLE SIGN IN
##################################################################################################
APPLE_KEY_ID = 'X5MLZU2APN'
APPLE_TEAM_ID = '37NTVURJ33'
APPLE_CLIENT_ID = 'com.nestsmarter.ios.customer'
APPLE_PRIVATE_KEY = """
-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgv8mDxxxkHV3IPmQ+
8Ama0d+BXMd/qxuce8wK6C0UH2egCgYIKoZIzj0DAQehRANCAATjPcRYrbeSyDz/
5T5JH0/zEtkaxw37HuD9VVhvqLnyX6QFr+FdV4HL+5Mlwa5hYPoLX3HuV4NppdPX
imOC7c1s
-----END PRIVATE KEY-----
"""

##################################################################################################
# QuickBlox
##################################################################################################
QUICKBLOX_DEFAULT_USER_PASSWORD = "hgP67!)h3gjh"
QUICKBLOX_APP_ID = 95628
QUICKBLOX_AUTH_KEY = 'jVtn7XHbj68tM9C'
QUICKBLOX_SECRET_KEY = 'y2Wq3NSnZ5CfabW'
QUICKBLOX_ACCOUNT_KEY = 'fy4WeKRbt9qusioBkzK-'

##################################################################################################
# Slipstream/Home junction MLS
##################################################################################################
MLS_AUTH_KEY = "s9-9a51194d-bc06-49f3-aa23-0f0551a5415d"
